"""empty message

Revision ID: cd2114fc08d1
Revises: ff1fdb592120
Create Date: 2019-08-02 08:31:43.932219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd2114fc08d1'
down_revision = 'ff1fdb592120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('slug', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'slug')
    # ### end Alembic commands ###
