"""empty message

Revision ID: 464e0e8dd7f9
Revises: cd2114fc08d1
Create Date: 2019-08-03 04:05:57.305793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464e0e8dd7f9'
down_revision = 'cd2114fc08d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.drop_index('name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'user', ['name'], unique=True)
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
